okta:
  oauth2:
    issuer: ${ISSUER_ACEBOOK}
    client-id: ${CLIENT_ID_ACEBOOK}
    client-secret: ${CLIENT_SECRET_ACEBOOK}

upload:
  profile: ${UPLOAD_PROFILE_PATH}
  posts: ${UPLOAD_POSTS_PATH}

spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: makersbnbgsai@gmail.com
    password: iqjkzweqdhujuwyr
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true